kiegroup/drools-ansible-rulebook-integration

.github/workflows/pre-release.yml, .github/workflows/release.yml, drools-ansible-rulebook-integration-runtime/pom.xml
- GHA: pre-release + release actions (includes #1)
- Use shade-maven-plugin instead of Quarkus uber-jar
=> Use shade maven plugin + Update GHA

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/RulesExecutor.java, drools-ansible-rulebook-integration-runtime/src/main/java/org/drools/ansible/rulebook/integration/core/jpy/AstRulesEngine.java
- GHA: pre-release + release actions
- Use shade-maven-plugin instead of Quarkus uber-jar
- fix: only upload shaded jar
- WIP: Pseudo-Clock
=> Add pseudo clock option to the surface API

README.md
Probably the README was written in the early stage of development. I update it to
- Fix json payload to run successfully
- Clarify the instruction to run `drools-ansible-rulebook-integration-core-rest`
=> Fix payload in README and easier instruction

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/Rule.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/RuleGenerationContext.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/RulesSet.java
Hello, this is mostly an exercise following today's presentation.
I am trying to move Executable Model generation away from Rule into RuleGenerationContext.
I have moved most of the properties.
This is a WIP for discussion
=> Separating parsing and generation

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/nightly-build-config.yaml, .github/workflows/pr-backporting.yml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1981
**Change Description**:
Setup nightly pipeline for `drools-ansible-rulebook-integration` project.
> NOTE: Also added PR backporting workflow.
**Referenced Pull Requests:**
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/267
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/15/
- https://github.com/kiegroup/kie-ci/pull/1450
> NOTE: https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/267 must be merged before merging this one
=> [BXMSPROD-1981] setup nightly

.ci/jenkins/Jenkinsfile.prod.nightly
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1981
=> Renamed nightly parameter to NEXUS_DEPLOYMENT_REPO_URL

drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternAdditionTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternBindingTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternLogicalOperatorsTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternRelationalOperatorsTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternSelectTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/ToPatternTestBase.java
Added logical operator tests and relational operator tests.
=> [DROOLS-7374] Add ConditionToPatternTest : 1st round

README.md, drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-core-rest/pom.xml, drools-ansible-rulebook-integration-durable-rest/pom.xml, drools-ansible-rulebook-integration-durable/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
Related PR:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/24
=> bump version 1.0.1-SNAPSHOT

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/project-dependencies.yaml
**Backport:** https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/35
=> [1.0.x] Nightly: fix how current version is fetched from pom

drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/domain/constraints/SelectConstraintTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternAdditionTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternBindingTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternLogicalOperatorsTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternRelationalOperatorsTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternSelectTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/ToPatternTestBase.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/utils/TestUtils.java
Only adding `SelectConstraintTest` as the first step
=> [DROOLS-7417] Add Constraint test : 1st round

drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/ToExecModelRulesOnceAfterTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/utils/TestUtils.java
=> [DROOLS-7447] Add OnceAfterDefinition test

README.md, drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-core-rest/pom.xml, drools-ansible-rulebook-integration-durable-rest/pom.xml, drools-ansible-rulebook-integration-durable/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/51
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/50
=> bump to version 1.0.3-SNAPSHOT

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/RulesSet.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/TimeAmount.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AbstractRulesEvaluator.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AutomaticPseudoClock.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AutomaticPseudoClockFactory.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesExecutorSession.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SlowAutomaticPseudoClock.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Main.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Payload.java, drools-ansible-rulebook-integration-main/src/main/resources/56_once_after.json, drools-ansible-rulebook-integration-main/src/test/java/org/drools/ansible/rulebook/integration/api/rulesengine/SlowAutomaticPseudoClock.java, drools-ansible-rulebook-integration-main/src/test/java/org/drools/ansible/rulebook/integration/api/rulesengine/SlowAutomaticPseudoClockFactory.java, drools-ansible-rulebook-integration-main/src/test/java/org/drools/ansible/rulebook/integration/main/PerfTest.java, drools-ansible-rulebook-integration-main/src/test/java/org/drools/ansible/rulebook/integration/main/SlownessTest.java, drools-ansible-rulebook-integration-main/src/test/java/org/drools/ansible/rulebook/integration/main/utils/StringPrintStream.java, drools-ansible-rulebook-integration-main/src/test/resources/META-INF/services/org.drools.ansible.rulebook.integration.api.rulesengine.AutomaticPseudoClockFactory, drools-ansible-rulebook-integration-main/src/test/resources/simplelogger.properties
- Slowness Test
- Warn log for delayed rule fire
=> Warn log for delayed rule fire

drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-protoextractor/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
followup to: 
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/61#discussion_r1263676989
=> inherit the version from drools pom directly

drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-protoextractor/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, pom.xml
- cleanup build plugins pom.xml(s) following OSSRH
- add "sufficient metadata" per convention OSSRH 
see also https://central.sonatype.org/publish/requirements
=> cleanup build plugins pom.xml(s) following OSSRH

pom.xml
=> bump drools to 8.44.0-SNAPSHOT

.ci/project-dependencies.yaml
=> Change 1.0.x drools mapping to 8.43.x

README.md, drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-core-rest/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-protoextractor/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/75
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/76
=> bump to version 1.0.4-SNAPSHOT

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/nightly-build-config.yaml
Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/103
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/104
=> [BXMSPROD-2209] move prod nightly to use rhel8

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/nightly-build-config.yaml
Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/103
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/104
=> [1.0.x][BXMSPROD-2209] move prod nightly to use rhel8

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesSetEventStructure.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/EventStructureSuggestionTest.java
- trim node path
- Handle event list
- accept array without bracket
=> [DROOLS-7636] ansible-rulebook : event structure suggestion

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AbstractRulesEvaluator.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java
Backport https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/132 to 1.0.x
=> [1.0.x] Backport Memory leak with unmatch events

.ci/jenkins/Jenkinsfile.prod.nightly, .ci/project-dependencies.yaml, .github/workflows/pre-release.yml, pom.xml
Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/137
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/136
=> [1.0.x] Align with drools 9.103.x-prod

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/RulesExecutor.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AbstractRulesEvaluator.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/MemoryMonitorUtil.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesEvaluator.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesExecutorSession.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStats.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/SessionStatsTest.java
https://issues.redhat.com/browse/DROOLS-7646
Add "peakMemory" to SessionStats, which records the highest value of the used memory.
=> [DROOLS-7646] Add peakMemory to SessionStats

drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/RulesExecutor.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AbstractRulesEvaluator.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/MemoryMonitorUtil.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesEvaluator.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesExecutorSession.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStats.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/SessionStatsTest.java, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-core-rest/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-protoextractor/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
Backport
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/134
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/135
to 1.0.x
And bump to `1.0.8-SNAPSHOT`
=> [1.0.x] backport baseLevelMemory and peakMemory

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/AccumulateWithinDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/OnceAfterDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/Throttle.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/TimeConstraint.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/TimedOutDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/AccumulateWithinTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/OnceAfterTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/OnceWithinTest.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Main.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Payload.java, drools-ansible-rulebook-integration-main/src/main/resources/test_accumulate_within_ast.json
- Added `AccumulateWithinDefinition`. See its class comment for the synthetic rule generation.
=> [DROOLS-7649] Support accumulate_within and threshold

drools-ansible-rulebook-integration-api/pom.xml, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/AccumulateWithinDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/OnceAfterDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/Throttle.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/TimeConstraint.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/temporal/TimedOutDefinition.java, drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/AccumulateWithinTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/OnceAfterTest.java, drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/OnceWithinTest.java, drools-ansible-rulebook-integration-benchmark/pom.xml, drools-ansible-rulebook-integration-core-rest/pom.xml, drools-ansible-rulebook-integration-main/pom.xml, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Main.java, drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/Payload.java, drools-ansible-rulebook-integration-main/src/main/resources/test_accumulate_within_ast.json, drools-ansible-rulebook-integration-protoextractor/pom.xml, drools-ansible-rulebook-integration-runtime/pom.xml, drools-ansible-rulebook-integration-tests/pom.xml, pom.xml
- backport of https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/147 to `1.0.x`
- bumped to `1.0.10-SNAPSHOT`
=> [1.0.x] [DROOLS-7649] Support accumulate_within and threshold
