kiegroup/drools-ansible-rulebook-integration

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/ListContainsConstraint.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/Operators.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/ListContainsTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/LogicalOperatorsTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/domain/constraints/ListContainsConstraintTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/MapConditionToPatternRelationalOperatorsTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/toexecmodel/ToPatternTestBase.java

https://issues.redhat.com/browse/DROOLS-7414
In Ansible Integration, 1.0 and 1.00 are not equal.
`ListContainsExpression` uses `org.drools.ansible.rulebook.integration.api.domain.constraints.Operators.areNumericEqual`
`EqualsExpression` uses `org.drools.model.Index.areNumericEqual`
This PR is to move methods including `areNumericEqual` from `Index` to new `OperatorUtils` and let both `ListContainsExpression` and `EqualsExpression` use `OperatorUtils`.
**referenced Pull Requests**: 
* https://github.com/kiegroup/drools/pull/5194

[DROOLS-7414] BigDecimal equality with different scale

---

drools-ansible-rulebook-integration-runtime/src/main/resources/simplelogger.properties

https://issues.redhat.com/browse/DROOLS-7434
Suppress `DefaultAgenda` debug log.
There are possible approaches:
1. Configure log level in `drools_jpy` : (pros) `drools_jpy` is a caller who can control log levels. (cons) `drools_jpy` manipulates String for  JVM options in `ruleset.py` so it could be a little messy
2. Include simplelogger.properties in drools-ansible-rulebook-integration-runtime jar : (pros) Hide the details that probably `drools_jpy` doesn't need to know. 
3. Change the log level of those messages to TRACE in `drools-core` : (pros) The log may be too verbose to other use cases.
This PR chooses 2.
Confirmed with `drools_jpy` locally that the change suppresses the DefaultAgenda debug logs.
Note: `drools_jpy` can overwrite the simpleLogger configurations with providing system …

[DROOLS-7434] Suppress DefaultAgenda debug log

---

.ci/project-dependencies.yaml

**Backport:** https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/31

[1.0.x] Upgrade nightly drools mapping to 8.38.x on nightly

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AutomaticPseudoClock.java

Now the Timer thread wouldn't be affected by other threads. However, if the Timer thread itself is slow or the entire process is slow, it's still possible to diverge from the real clock. It's good to log warnings in such a case for investigation. 
Note: `AutomaticPseudoClock` uses `ScheduledThreadPoolExecutor.scheduleAtFixedRate` which will quickly fill the gap in the case.

Log warn when pseudo clock is diverged from real clock

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/AutomaticPseudoClock.java

Ahh, Here it shouldn't`return`. For example, if there is 1000ms delay, `advancePseudoClock` just calculates `nextTick` to catch up with the real clock. Until catching up, it wouldn't advance ksession's actual pseudo clock and call fireAllRules...

Execute scheduledAdvanceTimeToMills even when Pseudo clock is diverged

---

drools-ansible-rulebook-integration-benchmark/pom.xml
drools-ansible-rulebook-integration-runtime/pom.xml

**JIRA**: https://issues.redhat.com/browse/DROOLS-7456
**referenced Pull Requests**: 
* requires first a new version of MVEL: https://github.com/mvel/mvel/pull/330
* https://github.com/kiegroup/drools/pull/5267
* https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/48
**Details**:
* drools-ecj is de-shaded, so shading `ECJ` as a dependency the new version containing checksum requires dropping these files from the `ECJ artifact` when building the bundled uber-jar / fat jar creation.

DROOLS-7456 avoid kie maven plugin to crash on jdk17 project

---

pom.xml

This bump is also required to run healthy CI.

bump drools to 8.42.0-SNAPSHOT

---

pom.xml

Problem
an (external?) contributor or a kiegroup member without a custom `~/.m2/settings.xml` set with explicit jboss nexus, would not be able to make the build out of the box:
This is because Drools snapshot are published only to jboss nexus, not to maven central.
Further, GHA does not have this problem simply because, correctly, they checkout Drools and build it fast as part of the CI on this repo.
But this is a problem for the personas identified above.
Solution
Implement repo explicitly in `pom.xml`, similarly to other repo/projects in kiegroup.

simplify repo lookup for contributors

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/io/JsonMapper.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/ArrayAccessTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/LogicalOperatorsTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MultipleConditionTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/NullTest.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/SimpleLogicalOperatorsTest.java

ref https://issues.redhat.com/browse/DROOLS-7514
Tested locally by:
Step1: on this project
```
mvn clean install
cp drools-ansible-rulebook-integration-runtime/target/drools-ansible-rulebook-integration-runtime-1.0.3-SNAPSHOT.jar ../drools_jpy/src/drools/jars/
```
Step2: on drools_jpy "pretend" an ad-hoc version
```
pytest -vv -s
python3 -m pip install .
```
(note: using "same" venv between drools_jpy and ansible-rulebook)
Step3: on ansible-rulebook "pretend" to use the "pretend-drools-jpy-version" and check the same commands per ansible-rulebook CI on GitHub action:
```
pip install -e .
pip install -r requirements_dev.txt
pytest -m "e2e" -n auto 
pytest -m "not e2e and not long_run" -vv -n auto
```
(the only 1 failure in the last screenshot is indeed due to the "pretend" version since …

DROOLS-7514 strict JSON parsing with Jackson

---

README.md

mark down notes from
https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/64
in readme

readme notes e2e testings

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/RuleConfigurationOption.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/RulesExecutorFactory.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/OnceAfterTest.java

When the option is set, there is no automatic advance of the internal pseudoclock. This option is intended for use in testing
(avoid during debug session for the pseudoclock to diverge because of the default automatic advancements).
Before:
Notice the log lines of pseudo-clock diverging, because the human user is taking the time while debugging
After:
Notice no lines of pseudo-clock diverged warnings.

Introduce fully manual pseudoclock opt (no auto advance)

---

.ci/jenkins/Jenkinsfile.prod.nightly

This change is related to https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/68

update Jenkinsfile.prod.nightly to use jdk17

---

drools-ansible-rulebook-integration-protoextractor/pom.xml

In order to avoid a wrong version inherited from productized drools `build-parent/pom.xml`, use the explicit antlr4 version.

explicit antlr4 version

---

drools-ansible-rulebook-integration-protoextractor/pom.xml
pom.xml

This dependencyManagement makes sure to use the expected antlr4 version in all sub modules.
https://issues.redhat.com/browse/DROOLS-7575

[DROOLS-7575] ansible-drools-integration incompatible ANTLR : 2nd round

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/MemoryMonitorUtil.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStats.java

@tkobayas These are the minor changes that I agreed with Madhu during yesterday's call. Even though the memory occupation doesn't belong to a single session but it's referred to the whole JVM, he said that it would be interesting to have that value reported among the session stats. In future, in case we will find more of these values referred to the entire system, we may want to add a proper `SystemStats` object and move also the memory stats there. Moreover he wanted the possibility to optionally kill the JVM when the memory threshold is reached. I'm not entirely sure if how I implemented this makes sense or there is a better alternative, so please double check it and feel free to propose better options.

[DROOLS-7589] add memory occupation to session stats + optionally exit above memory threshold

---

.ci/project-dependencies.yaml
.ci/pull-request-config.yaml
.github/workflows/pre-release.yml
.github/workflows/release.yml
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/conditions/AstCondition.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/conditions/MapCondition.java
drools-ansible-rulebook-integration-visualization/pom.xml
drools-ansible-rulebook-integration-visualization/src/main/java/org/drools/ansible/rulebook/integration/visualization/parser/LhsParser.java
drools-ansible-rulebook-integration-visualization/src/main/java/org/drools/ansible/rulebook/integration/visualization/parser/RhsParser.java
drools-ansible-rulebook-integration-visualization/src/main/java/org/drools/ansible/rulebook/integration/visualization/parser/RulesSetParser.java
drools-ansible-rulebook-integration-visualization/src/main/resources/simplelogger.properties
drools-ansible-rulebook-integration-visualization/src/test/java/org/drools/ansible/rulebook/integration/visualization/parser/ParserTest.java
drools-ansible-rulebook-integration-visualization/src/test/resources/simplelogger.properties
pom.xml

- Quick prototype. Works for a basic example : ParserTest
Requires https://github.com/apache/incubator-kie-drools/pull/5594 to compile and run. `drools` and `drools-ansible-rulebook-integration` have different upstream repos ,so cross-repository build wouldn't work, hence this CI should fail until https://github.com/apache/incubator-kie-drools/pull/5594 is merged.

[DROOLS-7578] Evaluate Impact analysis for ansible integration rules

---

.ci/project-dependencies.yaml
.ci/pull-request-config.yaml
.github/workflows/pre-release.yml
.github/workflows/release.yml

Issue: https://github.com/kiegroup/drools-ansible-rulebook-integration/issues/113
Hi @rgdoliveira , I'd like to solve the above issue.
When we run a GHA PR check for apache/incubator-kie-drools `10.0.x` branch, it cannot find the association with drools 10.0.x, so I added the entry here. Is this the right approach?
The GHA yml is:
https://github.com/apache/incubator-kie-drools/blob/10.0.x/.github/workflows/pr-drools-ansible.yml
Also I wonder if we can use `apache/incubator-kie-drools` instead of `kiegroup/drools` for the PR check. But I remember that you wanted to use  `kiegroup/drools` for productization needs (https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/101). Please kindly share your thought on this.
One more note, if we need to stick to  `kiegroup/drools` , …

[incubator-kie-drools-6100] Adjust drools-ansible integration GHA

---

.ci/jenkins/Jenkinsfile.prod.nightly
.ci/project-dependencies.yaml

Consider dependency drools version for drools-ansible-rulebook-integration 1.0.x
https://github.com/kiegroup/drools-ansible-rulebook-integration/issues/113

[1.0.x][drools-ansible-rulebook-integration-113] Adjust project dependencies for build-chain

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/LogUtil.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/RuleGenerationContext.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/conditions/MapCondition.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/RulebookConstraintOperator.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/RulebookOperator.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/StringPrintStream.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/TypeMismatchTest.java
drools-ansible-rulebook-integration-visualization/src/test/java/org/drools/ansible/rulebook/integration/visualization/parser/ParserTest.java

This draft PR requires
https://github.com/apache/incubator-kie-drools/pull/6104
to be built beforhand.
Cross repo PR check doesn't work for now.

[DROOLS-7635] ansible-rulebook : Raise an error when a condition compares incompatible types

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/LogUtil.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/RuleGenerationContext.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/conditions/MapCondition.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/NegationOperator.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/RulebookConstraintOperator.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/domain/constraints/RulebookOperator.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/StringPrintStream.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/TypeMismatchTest.java

This is a backport PR of https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/114 and https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/117 for 1.0.x
DO-NOT-MERGE until https://github.com/kiegroup/drools/pull/81 will be merged or we will decide to change the depending drools branch/version (which would require an update on this PR as well).
Until then, CI would fail with compilation errors.

[1.0.x][DROOLS-7635] ansible-rulebook : Raise an error when a condition compares incompatible types

---

drools-ansible-rulebook-integration-api/pom.xml
drools-ansible-rulebook-integration-benchmark/pom.xml
drools-ansible-rulebook-integration-core-rest/pom.xml
drools-ansible-rulebook-integration-main/pom.xml
drools-ansible-rulebook-integration-protoextractor/pom.xml
drools-ansible-rulebook-integration-runtime/pom.xml
drools-ansible-rulebook-integration-tests/pom.xml
drools-ansible-rulebook-integration-visualization/pom.xml
pom.xml

@mariofusco In order to clarify the difference from 1.0.x, isn't it better to bump the version to `2.0.0-SNAPSHOT` for main?

Bump version to 2.0.0-SNAPSHOT

---

.github/workflows/pre-release.yml

Updated pre-release.yml in 1.0.x branch to build and release latest 1.0.x jar, so that drools_jpy can consume.
Now we would have
- `Development Build` as the latest build of `main`. Now its version is `2.0.0-SNAPSHOT`
- `1.0.x Development Build` as the latest build of `1.0.x`. Now its version is `1.0.7-SNAPSHOT`

[1.0.x] Add 1.0.x prerelease GHA

---

.ci/project-dependencies.yaml

Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/130
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/129

align project-dependences.yaml with drools 9.102.x-prod

---

.ci/jenkins/Jenkinsfile.prod.nightly
.ci/project-dependencies.yaml
.github/workflows/pre-release.yml
pom.xml

Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/130
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/129

[1.0.x] Align with drools 9.102.x-prod

---

.ci/project-dependencies.yaml

Related PRs:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/137
- https://github.com/kiegroup/drools-ansible-rulebook-integration/pull/136

align project-dependences.yaml with drools 9.103.x-prod

---

drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/RulesExecutorSession.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStats.java
drools-ansible-rulebook-integration-api/src/main/java/org/drools/ansible/rulebook/integration/api/rulesengine/SessionStatsCollector.java
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/SessionStatsTest.java

https://issues.redhat.com/browse/DROOLS-7645
Add "baseLevelMemory" to SessionStats, which has the used memory size right after the ruleset loading (= kbase/ksession creation).

[DROOLS-7645] Add baseLevelMemory to SessionStats

---

drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java

Issue:
- https://github.com/kiegroup/drools-ansible-rulebook-integration/issues/140
Test only.
It takes a few minutes to finish, but you can easily confirm the heap trend via STDOUT.
```
Processed 0 events. Calling GC
usedMemory = 13958840
Processed 20 events. Calling GC
usedMemory = 14653592
Processed 40 events. Calling GC
usedMemory = 14990160
Processed 60 events. Calling GC
usedMemory = 15499176
Processed 80 events. Calling GC
usedMemory = 16003368
...
```

[drools-ansible-rulebook-integration-140] Memory Leak on dormant matches

---

.ci/jenkins/Jenkinsfile.prod.nightly
.ci/project-dependencies.yaml
.github/workflows/pre-release.yml
drools-ansible-rulebook-integration-api/pom.xml
drools-ansible-rulebook-integration-benchmark/pom.xml
drools-ansible-rulebook-integration-core-rest/pom.xml
drools-ansible-rulebook-integration-main/pom.xml
drools-ansible-rulebook-integration-protoextractor/pom.xml
drools-ansible-rulebook-integration-runtime/pom.xml
drools-ansible-rulebook-integration-tests/pom.xml
pom.xml

- Use drools 9.103.1 which contains the fix
- Bump to 1.0.9-SNAPSHOT
Manually confirmed that `load_test_all.sh` gives stable results, so the memory leak is fixed.

[1.0.x] [DROOLS-7647] Memory Leak with matching events after 1.0.7-SNAPSHOT

---

drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java

- Time constraint tests
- Removed large size events. Instead, increased loop count, so synthetic/control event leak can be detected easily
At the moment, all test methods in `MemoryLeakTest` is `@Disabled`, because such memory test results could be unstable. For now, I manually confirmed that the tests pass locally without memory leak. I'll consider CI strategy for MemoryLeakTest` in the next PR.

Add more memory leak tests

---

.github/workflows/pull-request.yml
Development_Notes.md
drools-ansible-rulebook-integration-api/pom.xml
drools-ansible-rulebook-integration-api/src/test/java/org/drools/ansible/rulebook/integration/api/MemoryLeakTest.java
drools-ansible-rulebook-integration-api/src/test/resources/simplelogger.properties
drools-ansible-rulebook-integration-main/load_test_all.sh
drools-ansible-rulebook-integration-main/src/main/java/org/drools/ansible/rulebook/integration/main/MemoryLeakAnalyzer.java
pom.xml

- `MemoryLeakTest` doesn't run by default.  It runs only with `-Pmemoryleak-tests`
- Added a job to run `MemoryLeakTest` and `load_test_all.sh` in GHA PR check
- Usually we want to avoid such load tests in a regular CI, but a memory issue is crucial to this project, so it's better to detect earlier. (Actually, these tests are not very slow, just a few minutes)
- Added `MemoryLeakAnalyzer` to check if there is any sign of memory leak in `load_test_all.sh` result. It helps the GHA

Gha memory leak test

---

drools-ansible-rulebook-integration-api/pom.xml
drools-ansible-rulebook-integration-benchmark/pom.xml
drools-ansible-rulebook-integration-core-rest/pom.xml
drools-ansible-rulebook-integration-main/pom.xml
drools-ansible-rulebook-integration-protoextractor/pom.xml
drools-ansible-rulebook-integration-runtime/pom.xml
drools-ansible-rulebook-integration-tests/pom.xml
drools-ansible-rulebook-integration-visualization/pom.xml
pom.xml

For now, the main branch is purely the latest development branch, which should not be consumed by drools_jpy. But `2.0.0-SNAPSHOT` is a little confusing, so drools_jpy had mistakenly picked it before.
Changing the version name to the explicitly development-like `999-SNAPSHOT`. Also it would align with the drools main version policy.

use 999-SNAPSHOT instead of 2.0.0-SNAPSHOT
